; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf, arduino
monitor_encoding = latin1
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
lib_deps = 
    lvgl/lvgl@^9.5.0
    bodmer/TFT_eSPI@^2.5.23
build_flags =
  -D USER_SETUP_LOADED=1
;  -D ILI9488_DRIVER=1
  -D ST7796_DRIVER
  -D TFT_MISO=19
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=21
  -D TFT_RST=4
;  -D TOUCH_CLK=14
;  -D TOUCH_CS=27
;  -D TOUCH_DIN=26
;  -D TOUCH_DO=25
;  -D TOUCH_IRQ=33
  -D LOAD_GLCD=1
  -D SPI_FREQUENCY=27000000
  -fexceptions
;  -D LV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"

build_unflags = -fno-exceptions